KDT3-miniproject-team1/frontend

.eslintrc.json, package-lock.json, package.json, src/pages/User.tsx
Close #15 
- 회원정보 수정 ui와 유효성 검증을 진행했습니다.
- 선택정보를 어떻게 받아와야 할지 고민 중입니다
- 의견 받아봅니다🧐
- 폼 구현을 위해서[ react-hook-form](https://react-hook-form.com/)을 설치하였습니다. 
- 유효성 검증을 위해 [yup](https://github.com/jquense/yup) 과 [zod](https://zod.dev/)를 사용해 봤는데 타입스크립트와 더 맞는 zod를 사용하는 것이 좋아 보입니다.
- 아 그리고 린트가 자꾸 npm i -S 로 하라고 잔소리해서, import/no-extraneous-dependencies 룰을 꺼버렸습니다. 
- 테스트나 개발 환경에서는 Dependency를 허용하도록
- 문구를 같이 정해봐야 할 거 같아요!
- 문구 정하기
- 나중에 api 요청 보낼때 성공을 어떻게 알릴지
=> Feat: 마이페이지 회원정보 수정 ui, 유효성 검증 진행중

src/components/myPage/Button.tsx
=> Feat: Button 컴포넌트 추가

src/components/Footer.tsx, src/components/Header.tsx, src/components/layout/Layout.tsx, src/components/mainContent/recommendList.tsx, src/data/listData.json, src/global/globalStyles.ts, src/pages/Main.tsx, src/pages/Search.tsx
Close #7 
Close #22 
- 헤더 초기값 문자열로 변경
- 입력창을 감싸고 있는 div form으로 변경
- 헤더 푸터 고정 및 layout -> main 스타일 변경 (헤더를 고정하는 과정에서 헤더와 메인컨텐츠가 겹쳐서 패딩 값을 변경하였습니다.)
- 메인 ui
- 리스트 구조를 보기 위해 더미 데이터를 생성하였습니다.
- 로그인 / 회원가입 버튼 페이지 이동
- 추천 상품 클릭시 상세 페이지로 이동
https://user-images.githubusercontent.com/107393773/219367141-d61e828e-b5e1-4305-aa3c-f12d212e8239.mov
- 헤더에서 검색을 하면 주소가 /search/헬로?search= 이렇게 가는데 ?search를 어떻게 빼야 할지 모르겠습니다. 😭
=> Feat: 헤더 수정 및 메인 완료 (비회원용)

src/components/ItemList.tsx, src/pages/Main.tsx
Remove: 컴포넌트 생성에 따른 추천 리스트 삭제
Close #
- ItemList 컴포넌트 생성 및 추천 리스트 삭제
- 그 외 navigate, style 수정
=> Feat: ItemList 컴포넌트 생성

src/components/SkeletonUi.tsx, src/pages/Likes.tsx, src/pages/MyPage.tsx
Close #17
- 정민님이 만든 리스트를 활용해  관심 상품 ui를 만들어 봤습니다.
- 로딩시 스켈레톤 ui를 추가해 봤습니다.
- 푸터가 fixed라 아이템을 가리는 버그가 있습니다!
- SkeletonUi, Likes 파일만 봐주시면 될 거 같습니다
=>  Feat: 관심 상품 ui, 스켈레톤 진행중 

src/components/Footer.tsx, src/components/Header.tsx, src/pages/Main.tsx, src/pages/Search.tsx
Close #30 
- 탭을 통해 검색 페이지로 이동 / 헤더 입력창을 통해 검색 페이지로 이동 (검색 결과가 있을 경우 / 없을 경우) 총 3가지로 나눠서 작업하였습니다.
- 검색 페이지 또한 ListItem을 사용하였습니다.
- 다른 페이지에서 검색을 통해 검색 페이지로 이동할 때 탭도 함께 이동하지 않던 오류 수정
=> Feat: 검색 페이지 && 탭

src/components/Footer.tsx
Close #43 
- 회원용 탭 ui 작업 완료 구분은 백엔드 배포 후 진행 예정입니다.
- 탭 이동 스타일 관련 오류 수정 완료하였습니다.
=> Feat: 탭 수정 완료

.gitignore, src/components/auth/CheckBoxButton.tsx, src/components/auth/InputModule.tsx, src/components/auth/SecurityNumberInput.tsx, src/components/layout/GotoBackLayout.tsx, src/global/FigmaStyles.tsx, src/global/globalStyles.ts, src/pages/SignIn.tsx, src/pages/SingUp.tsx, src/router/Router.tsx
Close #39
- 화면이 길어지는데 App이 height 100vh 이여서 수정
=> 회원 가입 페이지 추가 

src/pages/SingUp.tsx
=> feat : 0/7 삭제 , placeholder 추가

.gitignore, package.json, src/components/myPage/TextFiled.tsx, src/components/myPage/UserForm.tsx, src/pages/MyPage.tsx, src/pages/Password.tsx, src/pages/SingUp.tsx, src/router/Router.tsx
=> Feat: 비밀번호 확인 페이지 생성

package-lock.json, package.json, src/api/api.ts, src/index.tsx
Close #57
- react query를 사용하기 위한 프로바이더 추가
- 데브툴 추가
=> Feat: react query provider, devtool 추가

public/index.html, src/components/layout/Header.tsx, src/components/layout/PageHeader.tsx
Close #
- 프로젝트명 설정 Lonsily (Loan easily)
=> Feat: 프로젝트 이름 추가

package-lock.json, package.json, src/components/ItemList.tsx, src/components/Pagination.tsx, src/components/layout/Header.tsx, src/pages/Main.tsx, src/pages/Search.tsx
Close #64 
- 리스트에서 사용할 페이지 네이션 구현
사용 방법 (자세한 방법은 Search.tsx를 봐주세요)
```
import Pagination from "components/Pagination";
const [page, setPage] = useState<number>(1);
const limit = 4;
const offset = (page - 1) * limit;
{Array.isArray(result) ? (
<Pagination
total={result.length}
limit={limit}
page={page}
setPage={setPage}
/>
) : null}
```
https://user-images.githubusercontent.com/107393773/220614315-9a9f232d-25cd-4338-8aef-199fb741ecf6.mov
- Pagination.tsx 중간에 있는 ` // eslint-disable-next-line react/no-array-index-key` 는 map의 인자를 키로 받으면 안된다고 해서 넣었습니다.(어떤것을 키로 넣을지 생각이 않나서....ㅎ)
=> Feat: 페이지 네이션

src/api/api.ts, src/api/likes.ts, src/api/orders.ts, src/api/user.ts, src/components/ItemList.tsx, src/pages/Likes.tsx, src/pages/NotFound.tsx, src/types/itemType.ts
Close #68 
Close #69 
Close #71 
- 관심 상품 api 함수
- 주문 내역 api 함수
- 마이페이지 유저 관련 api 함수 러프하게 생성
- 토큰은 우선 하드코딩 해놨습니다.
- 아이템 타입 추가, 상세 정보도 추가했습니다.
- 리스트 컴포넌트에 타입을 추가했습니다.
- 아마 오류가 날 거 같은데 비동기로 받아온 데이터 넣어주면 해결될 거 같아요!
- 평균값이랑 대출 분류? 타입?은 우선 주석 처리 해놨습니다.
=>  Feat: 관심상품, 주문내역 api 함수 생성 , 아이템 타입 추가

src/api/main.ts, src/api/search.ts, src/components/ItemList.tsx, src/components/Pagination.tsx, src/pages/Cart.tsx, src/pages/Main.tsx, src/pages/Search.tsx, src/types/itemType.ts
Close #
- 검색 api 연결
- 비회원용 메인 추천 api 연결 완료 (전체 상품 리스트에서 5개 잘랐습니다.)
- 회원 이름과 맞춤 추천은 인증쪽 api 연결 후 연결 예정입니다
https://user-images.githubusercontent.com/107393773/220854278-51e21496-cb20-48ac-b5fd-e96cf14fa7ce.mov
- 장바구니, 관심상품, 검색 등등 리스트의 key값이 일치하지 않아서 ItemType이 길어졌습니다.
=> Feat: 검색, 비회원용 메인 추천 api 연결

src/api/api.ts, src/api/main.ts, src/api/search.ts, src/components/ItemList.tsx, src/components/dropDown.tsx, src/pages/Main.tsx, src/pages/Search.tsx
Close #
- 검색 리스트 이름순, 은행순으로 정렬
- 금리(평균)순도 추가할 예정입니다.
https://user-images.githubusercontent.com/107393773/220907406-ea886ed8-bcf9-4f7b-a288-8ca267ebd8c2.mov
=> Feat: 검색 리스트 드롭다운 정렬

.eslintrc.json, src/api/api.ts, src/api/likes.ts, src/api/orders.ts, src/pages/Likes.tsx, src/pages/MyPage.tsx, src/pages/Order.tsx, src/types/itemType.ts
Close #16 
Close #74 
Close #75 
Close #76 
Close #77 
Close #78 
Close #79
- 관심상품 신청내역 api 작업중
- 에러처리 성공처리 해야합니다.
- 관심상품의 경우  1개 남았을때 삭제 성공 되면
- Query data cannot be undefined. Please make sure to return a value other than undefined from your query function. Affected query key: ["like"] 라는 오류가 나는데 해결중입니다. -> 백엔드 데이터가 없어서 나는 문제 해결완
신청내역의 경우 관심상품과 ui동일
=> Feat: 관심상품 신청내역 api 작업중

src/api/carts.ts, src/api/productDetail.ts, src/components/ItemList.tsx, src/components/cart/OrderModal.tsx, src/data/productData.json, src/hooks/useCart.tsx, src/pages/Cart.tsx, src/pages/Likes.tsx, src/pages/Main.tsx, src/pages/ProductDetail.tsx, src/pages/SingUp.tsx
Close #72
장바구니 추가/삭제 기능을 구현했습니다.
상세페이지 api를 붙였습니다.
장바구니 로직이 복잡해서 hook으로 분리하려 해봤는데 .. 해결되지 못 한 타입 오류가 있었습니다
일단은 로직 구현을 우선으로 하고 추후 분리할게요
ui는 수정사항이 없어 스크린샷은 생략하겠습니다
=> Feat: 장바구니 추가/삭제, 상세페이지 api

src/components/ItemList.tsx, src/pages/ProductDetail.tsx
=> Feat: detailUrl 추가, mutation 추가

package.json
=> Env: build 명령어 수정

package.json
=> Env: build 명령어 복구

src/components/auth/SecurityNumberInput.tsx, src/pages/SingUp.tsx
=> fix : 잘못된 머지 수정

src/types/itemType.ts
=> Feat: 유니온 type 추가

package-lock.json, src/api/main.ts, src/api/productDetail.ts, src/components/layout/Footer.tsx, src/pages/Main.tsx, src/pages/ProductDetail.tsx, src/types/itemType.ts
Close #
- 메인페이지와 푸터를 회원정보조회 api 를 이용하여 구분하였습니다.
=> Feat: 메인, 푸터 회원/비회원 구분

src/api/api.ts, src/components/layout/PageHeader.tsx, src/router/PrivateRouter.tsx, src/router/PublicRouter.tsx, src/router/Router.tsx
Close #
- 인터셉터 잘 동작하는지 확인해봐야할듯
- 이제 로그인시 들어오는 유저 정보로 토큰 관리하면 될 거 같습니다
=>  Feat: api interceptors 추가 권한별 라우팅

src/components/ItemList.tsx, src/pages/MyPage.tsx, src/pages/SignIn.tsx, src/pages/SingUp.tsx
=>  Feat: 마이페이지 유저 정보 리덕스로 관리, 타입 오류 해결, 로그인, 회원가입시 로딩 제거

src/api/main.ts, src/components/layout/Footer.tsx, src/pages/Main.tsx, src/types/itemType.ts
=> Feat: 회원 정보 로컬스토리지 연결 완료

src/api/main.ts, src/components/layout/Footer.tsx, src/pages/Main.tsx
=> Feat: 메인 오류 수정

src/api/api.ts, src/api/carts.ts, src/api/likes.ts, src/api/main.ts, src/api/orders.ts, src/api/productDetail.ts, src/api/search.ts, src/app/store.ts, src/features/likeSlice.tsx, src/hooks/useLoginAxios.tsx, src/pages/Likes.tsx, src/pages/Main.tsx, src/pages/ProductDetail.tsx, src/router/Router.tsx
=> Feat: api 수정중, 관심상품 구현

src/api/api.ts
=> Refactor: withCredentials 추가

public/index.html
=>  Feat: upgrade-insecure-requests 추가 

README.md, public/index.html, src/api/api.ts, src/api/user.ts, src/components/myPage/UserForm.tsx, src/pages/MyPage.tsx, src/pages/Password.tsx, src/pages/SignIn.tsx, src/pages/SingUp.tsx, src/pages/User.tsx
=> 요청 데이터 수정, 회원 정보 로직 구현중.. 

src/api/user.ts, src/components/myPage/TextFiled.tsx, src/components/myPage/UserForm.tsx, src/features/authSlice.tsx, src/pages/Main.tsx, src/pages/MyPage.tsx, src/pages/Password.tsx, src/pages/ProductDetail.tsx, src/pages/User.tsx
Close #
- 회원정보 관련 api 작업 진행중
- 리덕스, api 관리 통일하고 고쳐야할듯....
=> Feat: 회원정보 관련 api 작업 진행중

src/pages/Main.tsx, src/pages/MyPage.tsx, src/pages/SingUp.tsx
=> Refactor: 유저 관리 리덕스로, 회원가입 후 로그인 페이지로 이동

src/api/user.ts, src/components/myPage/TextFiled.tsx, src/components/myPage/UserForm.tsx, src/features/authSlice.tsx, src/pages/MyPage.tsx, src/pages/Password.tsx, src/pages/SingUp.tsx, src/pages/User.tsx
=> Feat: 회원 정보 변경 진행중
